---
# tasks file for roles/launch_proxy
- name: Launch Proxy container
  docker_container:
    name: httpd
    image: camgvr/tp-devops-httpd:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
    networks:
      - name: my-network

