name: Deploy Application

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Deploy via Ansible
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml -u admin
