name: Backend Tests and SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn clean verify

      - name: Analyze with SonarCloud
        # S'exécute si les étapes précédentes ont réussi et que nous sommes sur la branche 'main'
        if: success() && github.ref == 'refs/heads/main'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd simple-api
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=cam640_tp-devops-git \
            -Dsonar.organization=cam640 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}